### PR TITLE
Use proper naming standards in codebase; See: websharks/alert-box-shortcode#2

### PR DESCRIPTION
**Pull request by kristineds**
Use proper naming standards; 
- [x] StudlyCaps for Class names: `AlertBox{}` instead of `Alert_Box{}`.
- [x] camelCase for Method names: `shortcode()`.
- [x] snake_case for Property and/or variable names: `$apply_shortcode`
- [x] Each class should be in a file of it's own, inside `src/includes/classes/AlertBox.php`
- [x] Each class should have a namespace declaration at the top that begins with: `WebSharks\WpSharks\` and contain a `\Classes` suffix as seen in this example.
- [x] Each PHP file should be compatible with PHP 7.0.4+
- [x] Class members written with OOP flexibility: `public function` instead of `public static function`

---

**Description: Provides a `[shortcode]` shortcode.**

screen shot 2016-05-06 at 12 49 20 am

See: websharks/alert-box-shortcode#2

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting my Pull Request. https://github.com/websharks/alert-box-shortcode/pull/6/commits/c9e3bdc50d9d34c1ca50cd42ee350b8eaa30c85c

I have commented out the line for declaring the strict types as it causes the shortcode to not work when I add it. Any ideas why? :) 

``` php
declare (strict_types = 1);
namespace WebSharks\WpSharks\AlertBoxShortcode\Classes;
```

**Comment by raamdev** [comment]
Any particular reason you're adding `declare (strict_types = 1);`? Isn't that a PHP7-only feature?

**Comment by jaswrks** [comment]
Lookin' great! :-) Here are some observations:
- [This line](https://github.com/websharks/alert-box-shortcode/blob/feature/2.1/alert-box-shortcode.php#L76-L77) is wrong; i.e., `casedefault` is invalid syntax.
  
  Instead, the `info` case should _also_ be the default.
  
  Remove:
  
  ``` php
    casedefault: // Invalid.
    break;
  ```
  
  Make `info` the default case handler also.
  
  ``` php
    case 'info':
    default: // Also default case.
        $attr['background_color'] = '#2ecc71';
        $attr['border_color']     = '#29b765';
        $attr['link_color']       = '#c0efd4';
        $attr['link_hover_color'] = '#f1f1f1';
        $class                    = 'dashicons dashicons-info';
        break;
  ```
- [This line](https://github.com/websharks/alert-box-shortcode/blob/feature/2.1/alert-box-shortcode.php#L129) has some problems. There is no shortcode named `shortcode` and there is no instance of the `AlertBox` class from which to call the `shortcode()` method in OOP fashion.
  
  ``` php
  add_shortcode('shortcode', array('AlertBox', 'shortcode'));
  ```
  
  It should be written like this:
  
  ``` php
  $GLOBALS[__NAMESPACE__] = new AlertBox();
  
  add_action('plugins_loaded', function () {
      add_shortcode('alert_box', [$GLOBALS[__NAMESPACE__], 'shortcode']);
  });
  ```
  
  Also, that block of code and the WP plugin headers should be the only thing in the file. The `AlertBox` class should get moved into a file of its own; i.e., PSR compliance states that each class must live in a file by itself.
  
  `/plugin.php` should contain:
  
  ``` php
    <?php
    /*
    Version: 160526
    Text Domain: alert-box-shortcode
    Plugin Name: Alert Box Shortcode
    Description: Provides an `[shortcode]` shortcode.
    Plugin URI: https://wordpress.org/plugins/alert-box-shortcode/
    Author: WP Sharks
    Author URI: https://wpsharks.com
    */
    declare (strict_types = 1);
    namespace WebSharks\WpSharks\AlertBoxShortcode;
  
    use WebSharks\WpSharks\AlertBoxShortcode\Classes;
  
    require_once __DIR__.'/src/includes/classes/AlertBox.php';
  
    $GLOBALS[__NAMESPACE__] = new Classes\AlertBox();
  
    add_action('plugins_loaded', function () {
        add_shortcode('alert_box', [$GLOBALS[__NAMESPACE__], 'shortcode']);
    });
  ```
  
  `src/includes/classes/AlertBox.php` should contain:
  
  ``` php
    <?php
    declare (strict_types = 1);
    namespace WebSharks\WpSharks\AlertBoxShortcode\Classes;
  
    class AlertBox
    {
        public function shortcode($attr, $content, $apply_shortcode)
        {
              ...
  ```

---

@kristineds writes...

> I have commented out the line for declaring the strict types as it causes the shortcode to not work when I add it. Any ideas why? :)

After the above changes, if you're still having trouble let me know what error the strict types declaration causes and I will help you troubleshoot the issue. Strict types are always better to have enabled when you're writing a PHP v7+ codebase, as it enforces strict types for all function parameters; i.e., it will raise an exception if you are passing the wrong data type between functions, which would otherwise go unchecked with strict types off; and that can lead to unreliable and unpredictable behavior.

@raamdev writes...

> Any particular reason you're adding declare (strict_types = 1);? Isn't that a PHP7-only feature?

I think she was following the suggestion that I made to add strict types for compatibility with the upcoming release of the WP Sharks Core. The Alert Box Shortcode plugin doesn't necessarily _need_ to be written in a way that conforms to the standards I'll be using in WPSC projects (i.e., this is a simple shortcode plugin), but as a learning exercise I was happy to see that she added it here.

All code that I write over the next few years will be designed to run on PHP v7.0.4 (or higher). The WebSharks Core, the WP Sharks Core, s2Member X, our websites, and several other libraries that are coming together to form the foundation of wpsharks.com are going to be written with the PHP v7.0.4 minimum requirement. So becoming familiar with strict types in PHP v7 will be very helpful.

In PHP, strict types prevent bugs caused by unexpected behavior. I have been forcing strict types in my code for several years now, but with PHP 7 we can enforce this at the interpreter level, and PHP v7 also enables the use of type hints for primitives that was previously not possible—making strict types a much more effective way to prevent problems associated with loose type comparison. See: http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict

**Comment by jaswrks** [comment]
With strict types enabled, most function parameters should be type-hinted also.

``` php
public function shortcode($attr, $content, $apply_shortcode)
```

Should become:

``` php
public function shortcode(array $attr, string $content = null, string $apply_shortcode = '')
```
- The first argument is required and it MUST be an array.
- The second argument is optional, but when passed it must be a `string` or `null`.
- The third argument is optional, but when passed it must be a `string`.

**Comment by jaswrks** [comment]
There should also be a return-type declaration on the `shortcode()` method.

What we have thus far, is:

``` php
public function shortcode(array $attr, string $content = null, string $apply_shortcode = '') {
```

This should become:

``` php
public function shortcode(array $attr, string $content = null, string $apply_shortcode = ''): string {
```

Note that `): string {` forces a strict return-type of `string`; i.e., the function MUST return a string, which is exactly what any caller would expect to receive from this function. We add the hint so that any changes to the code that might return anything other than a `string` will raise an exception and bring it to our attention quickly.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting my PR for this: https://github.com/websharks/alert-box-shortcode/pull/6/commits/d2a9f01edeba8ffbaa362226d538aa4e4c8289c9
- Also updated the description. Provides an `[alert_box]` shortcode.

screen shot 2016-05-16 at 2 07 07 am

**Comment by kristineds** [comment]
@jaswsinc @raamdev Any feedback on this? 😄  So we could start renaming the `000000-dev` branch to `dev` as mentioned here. https://github.com/websharks/alert-box-shortcode/issues/7

**Comment by jaswrks** [comment]
@kristineds This looks great to me!

**Comment by kristineds** [comment]
@raamdev Should I merge this into `000000-dev`? 😃

**Comment by jaswrks** [comment]
@kristineds Raam's going to be away on Friday so I thought I would try to help by responding here. Yep, I'd go ahead and do the merge and then you can rename the branch as outlined here under 'Attn: WebSharks Project Leads'. https://github.com/websharks/phings/issues/124

**Comment by kristineds** [comment]
Merged and closed! Thank you @jaswsinc and @raamdev! 😃

**Pull request merged**
